export const LANGS = [
  { id: "en", label: "English", dir: "ltr" },
  { id: "fa", label: "فارسی", dir: "rtl" },
  { id: "ar", label: "العربية", dir: "rtl" },
  { id: "es", label: "Español", dir: "ltr" },
  { id: "zh", label: "中文", dir: "ltr" },
  { id: "ko", label: "한국어", dir: "ltr" },
  { id: "ja", label: "日本語", dir: "ltr" },
  { id: "pt", label: "Português", dir: "ltr" },
  { id: "ru", label: "Русский", dir: "ltr" },
  { id: "tr", label: "Türkçe", dir: "ltr" },
  { id: "de", label: "Deutsch", dir: "ltr" },
  { id: "fr", label: "Français", dir: "ltr" },
] as const;

export type Lang = (typeof LANGS)[number]["id"];

export function isRtl(lang: Lang) {
  return lang === "fa" || lang === "ar";
}

export function detectLang(): Lang {
  try {
    const saved = localStorage.getItem("shareexact:lang");
    if (saved && LANGS.some((l) => l.id === saved)) return saved as Lang;
  } catch {
    /* private mode */
  }
  const nav = (typeof navigator !== "undefined" ? navigator.language || "" : "").toLowerCase();
  const hit = LANGS.find((l) => nav === l.id || nav.startsWith(`${l.id}-`));
  return hit?.id ?? "en";
}

const EN = {
  app: "ShareExact",
  kicker: "Robinhood Chain · precision + risk",
  tagline: "Exact shares. Programmable collateral. A brief before you look.",
  navBrief: "Brief",
  navHoldings: "Holdings",
  navThesis: "Thesis",
  navNight: "Night desk",
  navTransfer: "Exact send",
  navRisk: "Risk & credit",
  loadDesk: "Load sample desk",
  resetDesk: "Reset sample",
  connect: "Connect wallet",
  connected: "Connected",
  disconnect: "Disconnect",
  profile: "Profile",
  saveProfile: "Save profile",
  deskName: "Desk name",
  handle: "Handle",
  motto: "Motto",
  copyAddress: "Copy address",
  chain: "Robinhood Chain 4663",
  demoMode: "Sample desk",
  runBrief: "Run today’s brief",
  runWeekly: "Run weekly review",
  running: "Reading the book…",
  briefEmpty:
    "The desk will not guess. Run a brief when you want the book read — earnings, session, gap risk, and what to do with each line.",
  weeklyEmpty:
    "Weekly review checks every angle: concentration, after-hours drift, stale-oracle risk, and names that no longer match your thesis — including what to replace them with.",
  thesisHint: "State a belief. The desk maps it onto Stock Tokens that actually exist on chain 4663.",
  thesisPlaceholder: "AI infrastructure compounds for two more years, but I don’t want a single-name NVDA bet.",
  compose: "Compose basket",
  applyBasket: "Apply as paper book",
  nightIntro:
    "Wall Street sleeps. These tokens do not. Night desk is the after-hours tape: weekend gap, stale Chainlink prints, and the names that actually move while the cash session is dark.",
  transferIntro:
    "The number on a brokerage screen is not the number a wallet sends. ShareExact converts UI shares into the exact raw ERC-8056 amount before you sign — and refuses, rather than silently rounding.",
  amount: "Shares to send",
  recipient: "Recipient (blank = self)",
  preview: "Preview exact amount",
  sendDemo: "Record demo send",
  max: "Max",
  trapTitle: "What a naive wallet would send",
  exactTitle: "What the chain will move",
  holdingsIntro:
    "Share counts use the live UI multiplier, so the number matches a brokerage screen — not the raw ERC-20 figure in a generic wallet.",
  clickHint: "Open a name for the full angle list.",
  legal:
    "Not an offer of securities. Stock Tokens are tokenized debt securities issued by Robinhood Assets (Jersey) Limited, unavailable to US/UK/CA persons. Indicative marks for the desk demo. Not financial advice.",
  analyze: "Analyze this name",
  replace: "Replacement",
  hold: "Hold",
  trim: "Trim",
  add: "Add",
  stance: "Stance",
  session: "US cash session",
  value: "Book value",
  day: "Session P/L",
  nightPnl: "After-hours",
  multiplier: "UI multiplier",
  shares: "Shares",
  how: "How this works",
  pickWallet: "Choose a wallet",
  pickWalletBody:
    "ShareExact reads ACTIVE Robinhood Stock Tokens on chain 4663. It never takes custody of keys.",
  noWallet: "No browser wallet found. Install MetaMask or Rabby, unlock it, then return to this page.",
  scanning: "Reading Stock Tokens on 4663…",
  emptyBook: "This address holds no ACTIVE Stock Tokens on Robinhood Chain.",
  refreshBook: "Refresh holdings",
  switchNetwork: "Switch to Robinhood Chain",
  titleBrief: "A brief before you look.",
  titleHoldings: "The book, in brokerage shares.",
  titleThesis: "State a belief. Get a book.",
  titleNight: "The cash session is dark.",
  titleTransfer: "Send the number the chain will actually move.",
  help1:
    "Robinhood Stock Tokens show a brokerage share count. The wallet holds a different raw ERC-20 number. The ratio is the ERC-8056 UI multiplier — it moves after splits and reinvested dividends. Live case: CRWD is 4×. ShareExact converts before you sign and refuses rather than rounding.",
  help2:
    "The daily brief and weekly review read this book: session, after-hours drift, stale oracle risk, concentration, and replacements. Nothing runs until you press the button.",
  help3:
    "Thesis maps a sentence onto tokens on chain 4663. Night desk is the tape while NYSE is dark. Risk & credit turns exact units into collateral policy.",
  close: "Close",
  language: "Language",
  activity: "Activity",
  replacements: "Replacements",
  calendar: "Calendar",
  risks: "Risks",
  watchTonight: "Watch tonight",
  weight: "Weight",
  nameCol: "Name",
  tapeCol: "Tape",
  wrongChain: "Wallet is on the wrong network.",
  onChain: "On-chain book",
  sampleHint: "Tour with the sample desk, or connect a wallet that holds Stock Tokens.",
  foundInWallet: "names in this wallet",
  via: "via",
  titleRisk: "Stocks as collateral. Exact units first.",
  riskIntro:
    "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
  health: "Health",
  collateral: "Collateral capacity",
  borrow: "Credit line",
  utilization: "Utilization",
  leverage: "Leverage",
  concentration: "Concentration",
  volatility: "Volatility",
  judgePath: "Judge path",
  unlockLiquidity: "Unlock liquidity",
  stressBook: "Stress the book",
  playJudge: "Play 60s path",
  protect: "PROTECT",
  reduce: "REDUCE",
  monitor: "MONITOR",
  noAction: "NO ACTION",
  repay: "Repay",
  addCollateral: "Add collateral",
  corpAction: "Corporate action",
  runSplit: "Simulate AAPL 4:1 split",
  undoSplit: "Undo split",
  splitIntro:
    "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
  rawUnchanged: "Raw units unchanged",
  debtUnchanged: "Debt unchanged",
  exposureUnchanged: "Economic exposure unchanged",
  healthUnchanged: "Health unchanged — unlike a market shock",
  exactSendCta: "See the CRWD 4× trap",
  exactness: "Exactness",
  crwdTrap:
    "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
  borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
  safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
  passport: "RWA risk passport",
  registryLive: "official assets on 4663",
  liq: "Liquidation LTV",
  drawdown: "Drawdown",
  healthDropNote: "The model reacts to this book, not a generic headline.",
  stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
  dustBanner:
    "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
  unpriced: "No mark",
  dustBadge: "Dust book",
  prices: "Prices",
  indicativeMarks: "indicative demo marks — no feed configured",
  chainlinkOn: "Chainlink · chain 4663",
  sequencer: "sequencer",
  sequencerUp: "up",
  sequencerDown: "down",
  oldestPrint: "oldest print",
  unitUnreadable: "unit unreadable",
  blankSelf: "Blank = yourself",
  defaultDesk: "Desk",
  sendExact: "Send exact shares",
  instruction: "Instruction",
  whatWillMove: "What will move",
  readingToken: "Reading the token on chain…",
  insufficientRaw: "Raw wallet balance cannot cover this amount.",
  badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
  acceptLoss: "Accept the rounding shortfall to send.",
  acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
  unitUnknownDetail:
    "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
} as const;

type Dict = { [K in keyof typeof EN]: string };

export const COPY: Record<Lang, Dict> = {
  en: EN,
  fa: {
    app: "ShareExact",
    kicker: "Robinhood Chain · ۴۶۶۳",
    tagline: "سهم دقیق. بعد از بسته شدن بازار. یک بریف قبل از نگاه.",
    navBrief: "بریف",
    navHoldings: "سبد",
    navThesis: "تز",
    navNight: "میز شب",
    navTransfer: "ارسال دقیق",
    navRisk: "ریسک و اعتبار",
    loadDesk: "بارگذاری میز نمونه",
    resetDesk: "بازنشانی نمونه",
    connect: "اتصال کیف پول",
    connected: "متصل",
    disconnect: "قطع اتصال",
    profile: "پروفایل",
    saveProfile: "ذخیره پروفایل",
    deskName: "نام میز",
    handle: "شناسه",
    motto: "شعار",
    copyAddress: "کپی آدرس",
    chain: "زنجیره رابین‌هود ۴۶۶۳",

    demoMode: "میز نمونه",
    runBrief: "بریف امروز",
    runWeekly: "مرور هفتگی",
    running: "در حال خواندن دفتر…",
    briefEmpty:
      "میز حدس نمی‌زند. وقتی خواستید این دفتر خوانده شود — سود، جلسه، ریسک گپ و کار هر خط — بریف را اجرا کنید.",
    weeklyEmpty:
      "مرور هفتگی همه زاویه‌ها را چک می‌کند: تمرکز، رانش after-hours، اوراکل کهنه، و نمادهایی که دیگر با تز شما نمی‌خوانند — با پیشنهاد جایگزینی.",
    thesisHint: "یک باور بنویسید. میز آن را روی Stock Tokenهایی که واقعاً روی زنجیره ۴۶۶۳ هستند می‌نشاند.",
    thesisPlaceholder: "زیرساخت هوش مصنوعی دو سال دیگر مرکب می‌شود، اما نمی‌خواهم فقط روی NVDA شرط ببندم.",
    compose: "ساخت سبد",
    applyBasket: "اعمال به‌عنوان دفتر کاغذی",
    nightIntro:
      "وال‌استریت می‌خوابد. این توکن‌ها نه. میز شب نوار after-hours است: گپ آخر هفته، چاپ کهنه Chainlink، و نمادهایی که وقتی جلسه نقدی تاریک است واقعاً حرکت می‌کنند.",
    transferIntro:
      "عددی که روی صفحه کارگزاری می‌بینید همان عددی نیست که کیف پول می‌فرستد. ShareExact سهم نمایشی را به مقدار خام ERC-8056 تبدیل می‌کند و به‌جای گرد کردن خاموش، رد می‌کند.",
    amount: "سهام برای ارسال",
    recipient: "گیرنده (خالی = خودتان)",
    preview: "پیش‌نمایش مقدار دقیق",
    sendDemo: "ثبت ارسال آزمایشی",
    max: "حداکثر",
    trapTitle: "آنچه کیف پول ساده‌لوح می‌فرستد",
    exactTitle: "آنچه زنجیره جابه‌جا می‌کند",
    holdingsIntro:
      "تعداد سهام از ضریب نمایشی زنده استفاده می‌کند تا با صفحه کارگزاری یکی باشد — نه رقم خام ERC-20 در یک والت معمولی.",
    clickHint: "برای دیدن همه زاویه‌ها روی نماد بزنید.",
    legal:
      "پیشنهاد اوراق بهادار نیست. Stock Tokenها اوراق بدهی توکنایزشده‌اند و برای اشخاص آمریکا/بریتانیا/کانادا در دسترس نیستند. قیمت‌ها برای دموی میز، Indicative هستند. مشاوره مالی نیست.",
    analyze: "تحلیل این نماد",
    replace: "جایگزین",
    hold: "نگهدار",
    trim: "کاهش",
    add: "افزایش",
    stance: "موضع",
    session: "جلسه نقدی آمریکا",
    value: "ارزش دفتر",
    day: "سود و زیان جلسه",
    nightPnl: "After-hours",
    multiplier: "ضریب نمایشی",
    shares: "سهام",
    how: "چطور کار می‌کند",
    pickWallet: "کیف پول را انتخاب کنید",
    pickWalletBody: "ShareExact توکن‌های فعال سهام رابین‌هود را روی زنجیره ۴۶۶۳ می‌خواند. کلید را custodial نمی‌کند.",
    noWallet: "کیف پول مرورگر پیدا نشد. MetaMask یا Rabby را نصب و باز کنید، بعد به این صفحه برگردید.",
    scanning: "در حال خواندن Stock Tokenها روی ۴۶۶۳…",
    emptyBook: "این آدرس هیچ Stock Token فعال روی Robinhood Chain ندارد.",
    refreshBook: "تازه‌سازی سبد",
    switchNetwork: "تغییر به Robinhood Chain",
    titleBrief: "یک بریف قبل از نگاه.",
    titleHoldings: "دفتر، به سهم کارگزاری.",
    titleThesis: "یک باور بنویسید. یک دفتر بگیرید.",
    titleNight: "جلسه نقدی تاریک است.",
    titleTransfer: "عددی را بفرستید که زنجیره واقعاً جابه‌جا می‌کند.",
    help1:
      "Stock Tokenهای رابین‌هود تعداد سهم کارگزاری را نشان می‌دهند. والت عدد خام ERC-20 دیگری نگه می‌دارد. نسبت همان ضریب ERC-8056 است — بعد از split و سود تقسیمی حرکت می‌کند. مورد زنده: CRWD چهار برابر است. ShareExact قبل از امضا تبدیل می‌کند و به‌جای گرد کردن رد می‌کند.",
    help2:
      "بریف روزانه و مرور هفتگی این دفتر را می‌خوانند: جلسه، رانش after-hours، اوراکل کهنه، تمرکز و جایگزین. تا دکمه را نزنید چیزی اجرا نمی‌شود.",
    help3:
      "تز یک جمله را روی توکن‌های زنجیره ۴۶۶۳ می‌نشاند. میز شب نوار وقتی NYSE تاریک است — دلیل وجود این زنجیره.",
    close: "بستن",
    language: "زبان",
    activity: "فعالیت",
    replacements: "جایگزینی‌ها",
    calendar: "تقویم",
    risks: "ریسک‌ها",
    watchTonight: "امشب ببینید",
    weight: "وزن",
    nameCol: "نام",
    tapeCol: "نوار",
    wrongChain: "کیف پول روی شبکه اشتباه است.",
    onChain: "دفتر زنجیره",
    sampleHint: "با میز نمونه گشت بزنید، یا والت دارای Stock Token را وصل کنید.",
    foundInWallet: "نماد در این کیف پول",
    via: "از طریق",
    titleRisk: "سهام به‌عنوان وثیقه. اول واحد دقیق.",
    riskIntro: "موتور ریسک قطعی است: ضریب، تمرکز، نوسان و اهرم. هوش مصنوعی هدف را به سیاست ترجمه می‌کند. پول را حرکت نمی‌دهد.",
    health: "سلامت",
    collateral: "ظرفیت وثیقه",
    borrow: "خط اعتبار",
    utilization: "نرخ استفاده",
    leverage: "اهرم",
    concentration: "تمرکز",
    volatility: "نوسان",
    judgePath: "مسیر داور",
    unlockLiquidity: "آزاد کردن نقدینگی",
    stressBook: "استرس دفتر",
    playJudge: "پخش مسیر ۶۰ ثانیه",
    protect: "محافظت",
    reduce: "کاهش",
    monitor: "پایش",
    noAction: "بدون اقدام",
    repay: "بازپرداخت",
    addCollateral: "افزودن وثیقه",
    corpAction: "اقدام شرکتی",
    runSplit: "شبیه‌سازی split چهار به یک AAPL",
    undoSplit: "لغو split",
    splitIntro: "Split چهار به یک سهم نمایشی و ضریب ERC-8056 را زیاد، قیمت را کم، و واحد خام، بدهی، ارزش و سلامت را ثابت می‌گذارد.",
    rawUnchanged: "واحد خام بدون تغییر",
    debtUnchanged: "بدهی بدون تغییر",
    exposureUnchanged: "نمایش اقتصادی بدون تغییر",
    healthUnchanged: "سلامت بدون تغییر — برخلاف شوک بازار",
    exactSendCta: "تله ۴× CRWD را ببینید",
    exactness: "دقت واحد",
    crwdTrap: "ضریب نمایشی زنده CRWD چهار برابر است. ارسال عدد کارگزاری به‌صورت raw چهار برابر واحد اقتصادی را جابه‌جا می‌کند.",
    borrowHint: "خط اعتبار دمو — بدون vault زنده. کشیدن این اسلایدر باید سلامت را عوض کند. همین نکته است.",
    safetyRule: "هوش مصنوعی intent را ترجمه می‌کند. این موتور رقم را می‌سازد. قرارداد حد را نگه می‌دارد.",
    passport: "گذرنامه ریسک RWA",
    registryLive: "دارایی رسمی روی ۴۶۶۳",
    liq: "آستانه نقدشوندگی",
    drawdown: "افت",
    healthDropNote: "مدل به همین دفتر واکنش می‌دهد، نه به یک تیتر عمومی.",
    stressEmpty: "یک سناریو اجرا کنید. سلامت باید حرکت کند. بعد split — سلامت نباید.",
    dustBanner: "توکن‌های این کیف‌پول در حد غبار است. ریسک و اعتبار برای یک دفتر واقعی است — برای مسیر داور میز نمونه را بارگذاری کنید.",
    unpriced: "بدون قیمت",
    dustBadge: "دفتر غبار",
    prices: "قیمت‌ها",
    indicativeMarks: "قیمت‌های نمایشی — هیچ فید Chainlink پیکربندی نشده است",
    chainlinkOn: "Chainlink روی زنجیره ۴۶۶۳",
    sequencer: "سکوئنسر",
    sequencerUp: "فعال",
    sequencerDown: "قطع",
    oldestPrint: "قدیمی‌ترین چاپ",
    unitUnreadable: "ضریب ناخوانا",
    blankSelf: "خالی = برای خودتان",
    defaultDesk: "میز",
    sendExact: "ارسال سهم دقیق",
    instruction: "دستور",
    whatWillMove: "آنچه جابه‌جا می‌شود",
    readingToken: "در حال خواندن توکن از زنجیره…",
    insufficientRaw: "موجودی خام کیف پول برای این مقدار کافی نیست.",
    badRecipient: "آدرس گیرنده نامعتبر است. خالی بگذارید تا برای خودتان ارسال شود.",
    acceptLoss: "برای ارسال، کم‌شدن گردکردن را بپذیرید.",
    acceptShortfall: "این مقدار دقیق قابل نمایش نیست. کم شدن {n} وی از یک سهم را می‌پذیرم.",
    unitUnknownDetail:
      "ضریب این دارایی‌ها از خود توکن خوانده نشد. مقدار رجیستری فقط برای اطلاع است و هیچ انتقال سهم‌محوری روی آن‌ها اجرا نمی‌شود: نسبت ناشناخته ۱:۱ فرض نمی‌شود.",

  },
  ar: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "أسهم دقيقة. بعد الإغلاق. موجز قبل أن تنظر.",
    navBrief: "الموجز",
    navHoldings: "المحفظة",
    navThesis: "الأطروحة",
    navNight: "مكتب الليل",
    navTransfer: "إرسال دقيق",
    navRisk: "المخاطر والائتمان",
    loadDesk: "تحميل مكتب تجريبي",
    resetDesk: "إعادة العينة",
    connect: "ربط المحفظة",
    connected: "متصل",
    disconnect: "قطع الاتصال",
    profile: "الملف",
    saveProfile: "حفظ الملف",
    deskName: "اسم المكتب",
    handle: "المعرف",
    motto: "الشعار",
    copyAddress: "نسخ العنوان",
    chain: "سلسلة روبنهود ٤٦٦٣",

    demoMode: "مكتب تجريبي",
    runBrief: "موجز اليوم",
    runWeekly: "مراجعة أسبوعية",
    running: "جارٍ قراءة الدفتر…",
    briefEmpty: "المكتب لا يخمن. شغّل الموجز عندما تريد قراءة الدفتر.",
    weeklyEmpty: "المراجعة الأسبوعية تفحص التركيز وانحراف ما بعد الإغلاق ومخاطر الأوراكل.",
    thesisHint: "اكتب قناعة. يُسقطها المكتب على رموز موجودة على السلسلة 4663.",
    thesisPlaceholder: "بنية الذكاء الاصطناعي تتراكم سنتين إضافيتين، دون رهان منفرد على NVDA.",
    compose: "تكوين السلة",
    applyBasket: "تطبيق كدفتر ورقي",
    nightIntro: "وول ستريت نائمة. هذه الرموز لا. مكتب الليل هو شريط ما بعد الإغلاق.",
    transferIntro: "الرقم على شاشة الوسيط ليس الرقم الذي ترسله المحفظة. ShareExact يحوّل قبل التوقيع.",
    amount: "أسهم للإرسال",
    recipient: "المستلم (فارغ = أنت)",
    preview: "معاينة المبلغ الدقيق",
    sendDemo: "تسجيل إرسال تجريبي",
    max: "الحد الأقصى",
    trapTitle: "ما ترسله محفظة ساذجة",
    exactTitle: "ما ستحرّكه السلسلة",
    holdingsIntro: "عدد الأسهم يستخدم المضاعف الحي ليطابق شاشة الوسيط.",
    clickHint: "افتح رمزاً لقائمة الزوايا.",
    legal: "ليست عرضاً لأوراق مالية. علامات إرشادية للعرض. ليست مشورة مالية.",
    analyze: "تحليل هذا الرمز",
    replace: "بديل",
    hold: "احتفظ",
    trim: "خفّض",
    add: "زِد",
    stance: "الموقف",
    session: "جلسة النقد الأمريكية",
    value: "قيمة الدفتر",
    day: "ربح/خسارة الجلسة",
    nightPnl: "بعد الإغلاق",
    multiplier: "مضاعف الواجهة",
    shares: "أسهم",
    how: "كيف يعمل",
    pickWallet: "اختر محفظة",
    pickWalletBody: "يقرأ ShareExact رموز الأسهم النشطة على السلسلة 4663. لا يحفظ المفاتيح.",
    noWallet: "لا توجد محفظة متصفح. ثبّت MetaMask أو Rabby ثم عد.",
    scanning: "جارٍ قراءة الرموز على 4663…",
    emptyBook: "هذا العنوان لا يملك رموز أسهم نشطة على Robinhood Chain.",
    refreshBook: "تحديث المحفظة",
    switchNetwork: "التبديل إلى Robinhood Chain",
    titleBrief: "موجز قبل أن تنظر.",
    titleHoldings: "الدفتر، بأسهم الوسيط.",
    titleThesis: "اكتب قناعة. احصل على دفتر.",
    titleNight: "جلسة النقد مظلمة.",
    titleTransfer: "أرسل الرقم الذي ستحرّكه السلسلة فعلاً.",
    help1: "رموز Robinhood تعرض عدد أسهم الوسيط. المحفظة تحتفظ برقم ERC-20 خام مختلف. النسبة هي مضاعف ERC-8056. CRWD = 4×.",
    help2: "الموجز اليومي والأسبوعي يقرآن هذا الدفتر. لا شيء يعمل حتى تضغط الزر.",
    help3: "الأطروحة تُسقط جملة على رموز السلسلة 4663. مكتب الليل هو الشريط بينما NYSE مظلمة.",
    close: "إغلاق",
    language: "اللغة",
    activity: "النشاط",
    replacements: "البدائل",
    calendar: "التقويم",
    risks: "المخاطر",
    watchTonight: "راقب الليلة",
    weight: "الوزن",
    nameCol: "الاسم",
    tapeCol: "الشريط",
    wrongChain: "المحفظة على الشبكة الخطأ.",
    onChain: "دفتر السلسلة",
    sampleHint: "تجوّل بالمكتب التجريبي، أو اربط محفظة تحمل رموز الأسهم.",
    foundInWallet: "رموز في هذه المحفظة",
    via: "عبر",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  es: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "Acciones exactas. Fuera de horario. Un brief antes de mirar.",
    navBrief: "Brief",
    navHoldings: "Cartera",
    navThesis: "Tesis",
    navNight: "Mesa nocturna",
    navTransfer: "Envío exacto",
    navRisk: "Riesgo y crédito",
    loadDesk: "Cargar mesa de ejemplo",
    resetDesk: "Restablecer ejemplo",
    connect: "Conectar cartera",
    connected: "Conectado",
    disconnect: "Desconectar",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "Mesa de ejemplo",
    runBrief: "Brief de hoy",
    runWeekly: "Revisión semanal",
    running: "Leyendo el libro…",
    briefEmpty: "La mesa no adivina. Ejecuta un brief para leer el libro.",
    weeklyEmpty: "La revisión semanal cubre concentración, after-hours y oráculo obsoleto.",
    thesisHint: "Escribe una convicción. La mesa la mapea a tokens reales de la cadena 4663.",
    thesisPlaceholder: "La infraestructura de IA se capitaliza dos años más, sin una apuesta única en NVDA.",
    compose: "Componer cesta",
    applyBasket: "Aplicar como libro papel",
    nightIntro: "Wall Street duerme. Estos tokens no. La mesa nocturna es la cinta after-hours.",
    transferIntro: "El número en la pantalla del bróker no es el que envía la cartera. ShareExact convierte antes de firmar.",
    amount: "Acciones a enviar",
    recipient: "Destinatario (vacío = tú)",
    preview: "Previsualizar cantidad exacta",
    sendDemo: "Registrar envío demo",
    max: "Máx",
    trapTitle: "Lo que enviaría una cartera ingenua",
    exactTitle: "Lo que moverá la cadena",
    holdingsIntro: "El recuento usa el multiplicador UI en vivo para coincidir con la pantalla del bróker.",
    clickHint: "Abre un nombre para todos los ángulos.",
    legal: "No es una oferta de valores. Marcas indicativas. No es asesoramiento financiero.",
    analyze: "Analizar este nombre",
    replace: "Sustituto",
    hold: "Mantener",
    trim: "Reducir",
    add: "Añadir",
    stance: "Postura",
    session: "Sesión de efectivo EE.UU.",
    value: "Valor del libro",
    day: "P/L de sesión",
    nightPnl: "After-hours",
    multiplier: "Multiplicador UI",
    shares: "Acciones",
    how: "Cómo funciona",
    pickWallet: "Elige una cartera",
    pickWalletBody: "ShareExact lee Stock Tokens activos en la cadena 4663. No custodia claves.",
    noWallet: "No hay cartera de navegador. Instala MetaMask o Rabby y vuelve.",
    scanning: "Leyendo Stock Tokens en 4663…",
    emptyBook: "Esta dirección no tiene Stock Tokens activos en Robinhood Chain.",
    refreshBook: "Actualizar cartera",
    switchNetwork: "Cambiar a Robinhood Chain",
    titleBrief: "Un brief antes de mirar.",
    titleHoldings: "El libro, en acciones de bróker.",
    titleThesis: "Enuncia una creencia. Obtén un libro.",
    titleNight: "La sesión de efectivo está oscura.",
    titleTransfer: "Envía el número que la cadena realmente moverá.",
    help1: "Los Stock Tokens muestran acciones de bróker. La cartera guarda un ERC-20 crudo distinto. CRWD es 4×.",
    help2: "El brief diario y semanal leen este libro. Nada corre hasta que pulsas el botón.",
    help3: "La tesis mapea una frase a tokens de la 4663. La mesa nocturna es la cinta con NYSE a oscuras.",
    close: "Cerrar",
    language: "Idioma",
    activity: "Actividad",
    replacements: "Sustituciones",
    calendar: "Calendario",
    risks: "Riesgos",
    watchTonight: "Vigilar esta noche",
    weight: "Peso",
    nameCol: "Nombre",
    tapeCol: "Cinta",
    wrongChain: "La cartera está en la red incorrecta.",
    onChain: "Libro on-chain",
    sampleHint: "Recorre la mesa de ejemplo, o conecta una cartera con Stock Tokens.",
    foundInWallet: "nombres en esta cartera",
    via: "vía",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  zh: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "精确股数。盘后。先看简报。",
    navBrief: "简报",
    navHoldings: "持仓",
    navThesis: "论点",
    navNight: "夜盘",
    navTransfer: "精确发送",
    navRisk: "风险与信贷",
    loadDesk: "加载示例台",
    resetDesk: "重置示例",
    connect: "连接钱包",
    connected: "已连接",
    disconnect: "断开",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "示例台",
    runBrief: "今日简报",
    runWeekly: "每周复盘",
    running: "正在阅读持仓…",
    briefEmpty: "工作台不会猜测。需要阅读持仓时再运行简报。",
    weeklyEmpty: "每周复盘检查集中度、盘后漂移与过期预言机风险。",
    thesisHint: "写下判断。工作台会映射到 4663 链上真实存在的股票代币。",
    thesisPlaceholder: "AI 基建还能再复合两年，但我不想押单一的 NVDA。",
    compose: "生成篮子",
    applyBasket: "应用为纸面账本",
    nightIntro: "华尔街在睡。这些代币没有。夜盘是盘后行情带。",
    transferIntro: "券商屏幕上的数字不是钱包发送的数字。ShareExact 在签名前完成换算。",
    amount: "发送股数",
    recipient: "收款地址（空=自己）",
    preview: "预览精确数量",
    sendDemo: "记录演示发送",
    max: "最大",
    trapTitle: "朴素钱包会发送的数量",
    exactTitle: "链上实际会移动的数量",
    holdingsIntro: "股数使用实时 UI 乘数，以匹配券商屏幕，而非普通钱包中的原始 ERC-20。",
    clickHint: "打开某个标的查看全部角度。",
    legal: "不构成证券发行。演示用指示性价格。非投资建议。",
    analyze: "分析此标的",
    replace: "替代",
    hold: "持有",
    trim: "减仓",
    add: "加仓",
    stance: "立场",
    session: "美国现金时段",
    value: "账面价值",
    day: "时段盈亏",
    nightPnl: "盘后",
    multiplier: "UI 乘数",
    shares: "股数",
    how: "原理",
    pickWallet: "选择钱包",
    pickWalletBody: "ShareExact 读取 4663 链上的有效股票代币。不托管私钥。",
    noWallet: "未发现浏览器钱包。请安装 MetaMask 或 Rabby 后返回。",
    scanning: "正在读取 4663 上的股票代币…",
    emptyBook: "此地址在 Robinhood Chain 上没有有效股票代币。",
    refreshBook: "刷新持仓",
    switchNetwork: "切换到 Robinhood Chain",
    titleBrief: "先看简报。",
    titleHoldings: "以券商股数计的账本。",
    titleThesis: "陈述判断。得到账本。",
    titleNight: "现金时段已关闭。",
    titleTransfer: "发送链上真正会移动的数字。",
    help1: "Robinhood 股票代币显示券商股数。钱包持有不同的原始 ERC-20。CRWD 为 4 倍。",
    help2: "每日与每周简报会阅读此账本。按下按钮前不会运行。",
    help3: "论点把一句话映射到 4663 上的代币。夜盘是 NYSE 关闭时的行情带。",
    close: "关闭",
    language: "语言",
    activity: "活动",
    replacements: "替换",
    calendar: "日历",
    risks: "风险",
    watchTonight: "今晚关注",
    weight: "权重",
    nameCol: "名称",
    tapeCol: "行情带",
    wrongChain: "钱包不在正确网络。",
    onChain: "链上账本",
    sampleHint: "用示例台浏览，或连接持有股票代币的钱包。",
    foundInWallet: "个标的在此钱包",
    via: "通过",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  ko: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "정확한 주식 수. 시간외. 보기 전의 브리프.",
    navBrief: "브리프",
    navHoldings: "보유",
    navThesis: "테제",
    navNight: "나이트 데스크",
    navTransfer: "정확 전송",
    navRisk: "리스크와 신용",
    loadDesk: "샘플 데스크 불러오기",
    resetDesk: "샘플 재설정",
    connect: "지갑 연결",
    connected: "연결됨",
    disconnect: "연결 해제",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "샘플 데스크",
    runBrief: "오늘의 브리프",
    runWeekly: "주간 리뷰",
    running: "장부를 읽는 중…",
    briefEmpty: "데스크는 추측하지 않습니다. 장부를 읽으려면 브리프를 실행하세요.",
    weeklyEmpty: "주간 리뷰는 집중도, 시간외 드리프트, 오래된 오라클을 점검합니다.",
    thesisHint: "믿음을 적으세요. 데스크가 4663에 실제로 있는 토큰으로 매핑합니다.",
    thesisPlaceholder: "AI 인프라는 2년 더 복리지만 NVDA 단일 베팅은 싫다.",
    compose: "바스켓 구성",
    applyBasket: "페이퍼 북으로 적용",
    nightIntro: "월스트리트는 잡니다. 이 토큰은 아닙니다. 나이트 데스크는 시간외 테이프입니다.",
    transferIntro: "증권사 화면의 숫자는 지갑이 보내는 숫자가 아닙니다. 서명 전에 변환합니다.",
    amount: "보낼 주식 수",
    recipient: "수신자 (공란 = 본인)",
    preview: "정확한 수량 미리보기",
    sendDemo: "데모 전송 기록",
    max: "최대",
    trapTitle: "순진한 지갑이 보낼 수량",
    exactTitle: "체인이 실제로 옮길 수량",
    holdingsIntro: "주식 수는 실시간 UI 배율을 써서 증권사 화면과 맞춥니다.",
    clickHint: "종목을 열어 모든 각도를 보세요.",
    legal: "증권 공모가 아닙니다. 데모용 참고 시세. 투자 자문 아님.",
    analyze: "이 종목 분석",
    replace: "대체",
    hold: "보유",
    trim: "축소",
    add: "확대",
    stance: "포지션",
    session: "미국 현금 세션",
    value: "장부 가치",
    day: "세션 손익",
    nightPnl: "시간외",
    multiplier: "UI 배율",
    shares: "주식",
    how: "작동 방식",
    pickWallet: "지갑 선택",
    pickWalletBody: "ShareExact는 4663의 활성 주식 토큰을 읽습니다. 키를 보관하지 않습니다.",
    noWallet: "브라우저 지갑이 없습니다. MetaMask 또는 Rabby를 설치하세요.",
    scanning: "4663에서 주식 토큰을 읽는 중…",
    emptyBook: "이 주소는 Robinhood Chain에 활성 주식 토큰이 없습니다.",
    refreshBook: "보유 새로고침",
    switchNetwork: "Robinhood Chain으로 전환",
    titleBrief: "보기 전의 브리프.",
    titleHoldings: "증권사 주식 수로 된 장부.",
    titleThesis: "믿음을 말하세요. 장부를 받으세요.",
    titleNight: "현금 세션이 어둡습니다.",
    titleTransfer: "체인이 실제로 옮길 숫자를 보내세요.",
    help1: "Robinhood 주식 토큰은 증권사 주식 수를 보여 줍니다. 지갑은 다른 원시 ERC-20을 보유합니다. CRWD는 4배.",
    help2: "일간·주간 브리프가 이 장부를 읽습니다. 버튼을 누르기 전에는 실행되지 않습니다.",
    help3: "테제는 문장을 4663 토큰에 매핑합니다. 나이트 데스크는 NYSE가 닫힌 테이프입니다.",
    close: "닫기",
    language: "언어",
    activity: "활동",
    replacements: "교체",
    calendar: "캘린더",
    risks: "위험",
    watchTonight: "오늘 밤 관찰",
    weight: "비중",
    nameCol: "이름",
    tapeCol: "테이프",
    wrongChain: "지갑이 잘못된 네트워크에 있습니다.",
    onChain: "온체인 장부",
    sampleHint: "샘플 데스크로 둘러보거나 주식 토큰을 보유한 지갑을 연결하세요.",
    foundInWallet: "개 종목, 이 지갑",
    via: "통해",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  ja: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "正確な株数。時間外。見る前のブリーフ。",
    navBrief: "ブリーフ",
    navHoldings: "保有",
    navThesis: "テーゼ",
    navNight: "ナイトデスク",
    navTransfer: "正確送信",
    navRisk: "リスクとクレジット",
    loadDesk: "サンプルデスクを読込",
    resetDesk: "サンプルをリセット",
    connect: "ウォレット接続",
    connected: "接続済み",
    disconnect: "切断",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "サンプルデスク",
    runBrief: "本日のブリーフ",
    runWeekly: "週次レビュー",
    running: "帳簿を読んでいます…",
    briefEmpty: "デスクは推測しません。帳簿を読むときブリーフを実行してください。",
    weeklyEmpty: "週次レビューは集中度、時間外、古いオラクルを点検します。",
    thesisHint: "信念を書いてください。チェーン4663上の実在トークンに写します。",
    thesisPlaceholder: "AIインフラはあと2年複利だが、NVDA単一賭けはしない。",
    compose: "バスケット作成",
    applyBasket: "ペーパーブックとして適用",
    nightIntro: "ウォール街は眠る。トークンは眠らない。ナイトデスクは時間外テープです。",
    transferIntro: "証券画面の数字はウォレットが送る数字ではありません。署名前に換算します。",
    amount: "送る株数",
    recipient: "受取人（空欄＝自分）",
    preview: "正確な数量をプレビュー",
    sendDemo: "デモ送信を記録",
    max: "最大",
    trapTitle: "素朴なウォレットが送る量",
    exactTitle: "チェーンが実際に動かす量",
    holdingsIntro: "株数はライブUI倍率を使い、証券画面と一致させます。",
    clickHint: "銘柄を開いて全角度を見る。",
    legal: "有価証券の募集ではありません。デモ用の参考値。投資助言ではありません。",
    analyze: "この銘柄を分析",
    replace: "代替",
    hold: "保有",
    trim: "縮小",
    add: "追加",
    stance: "スタンス",
    session: "米国キャッシュセッション",
    value: "帳簿価値",
    day: "セッション損益",
    nightPnl: "時間外",
    multiplier: "UI倍率",
    shares: "株数",
    how: "仕組み",
    pickWallet: "ウォレットを選ぶ",
    pickWalletBody: "ShareExactは4663上のアクティブな株式トークンを読みます。鍵は預かりません。",
    noWallet: "ブラウザウォレットがありません。MetaMaskかRabbyを入れて戻ってください。",
    scanning: "4663の株式トークンを読み取り中…",
    emptyBook: "このアドレスはRobinhood Chain上にアクティブな株式トークンがありません。",
    refreshBook: "保有を更新",
    switchNetwork: "Robinhood Chainへ切替",
    titleBrief: "見る前のブリーフ。",
    titleHoldings: "証券株数で見た帳簿。",
    titleThesis: "信念を述べよ。帳簿を得よ。",
    titleNight: "キャッシュセッションは暗い。",
    titleTransfer: "チェーンが実際に動かす数字を送れ。",
    help1: "Robinhood株式トークンは証券株数を表示します。ウォレットは別の生ERC-20を持ちます。CRWDは4倍。",
    help2: "日次・週次ブリーフがこの帳簿を読みます。ボタンを押すまで動きません。",
    help3: "テーゼは一文を4663のトークンに写します。ナイトデスクはNYSEが閉じたテープです。",
    close: "閉じる",
    language: "言語",
    activity: "活動",
    replacements: "入替",
    calendar: "カレンダー",
    risks: "リスク",
    watchTonight: "今夜見る",
    weight: "比重",
    nameCol: "名称",
    tapeCol: "テープ",
    wrongChain: "ウォレットが別ネットワークです。",
    onChain: "オンチェーン帳簿",
    sampleHint: "サンプルデスクで見るか、株式トークンを持つウォレットを接続。",
    foundInWallet: "銘柄がこのウォレットに",
    via: "経由",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  pt: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "Ações exatas. After hours. Um brief antes de olhar.",
    navBrief: "Brief",
    navHoldings: "Carteira",
    navThesis: "Tese",
    navNight: "Mesa noturna",
    navTransfer: "Envio exato",
    navRisk: "Risco e crédito",
    loadDesk: "Carregar mesa de exemplo",
    resetDesk: "Repor exemplo",
    connect: "Ligar carteira",
    connected: "Ligado",
    disconnect: "Desligar",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "Mesa de exemplo",
    runBrief: "Brief de hoje",
    runWeekly: "Revisão semanal",
    running: "A ler o livro…",
    briefEmpty: "A mesa não adivinha. Execute um brief para ler o livro.",
    weeklyEmpty: "A revisão semanal cobre concentração, after-hours e oráculo velho.",
    thesisHint: "Escreva uma convicção. A mesa mapeia para tokens reais da chain 4663.",
    thesisPlaceholder: "A infra de IA capitaliza mais dois anos, mas sem uma aposta só em NVDA.",
    compose: "Compor cesta",
    applyBasket: "Aplicar como livro de papel",
    nightIntro: "Wall Street dorme. Estes tokens não. A mesa noturna é a fita after-hours.",
    transferIntro: "O número no ecrã da corretora não é o que a carteira envia. O ShareExact converte antes de assinar.",
    amount: "Ações a enviar",
    recipient: "Destinatário (vazio = você)",
    preview: "Pré-visualizar quantidade exata",
    sendDemo: "Registar envio demo",
    max: "Máx",
    trapTitle: "O que uma carteira ingénua enviaria",
    exactTitle: "O que a chain vai mover",
    holdingsIntro: "A contagem usa o multiplicador UI em direto para coincidir com o ecrã da corretora.",
    clickHint: "Abra um nome para todos os ângulos.",
    legal: "Não é oferta de valores. Marcas indicativas. Não é aconselhamento financeiro.",
    analyze: "Analisar este nome",
    replace: "Substituição",
    hold: "Manter",
    trim: "Reduzir",
    add: "Aumentar",
    stance: "Posição",
    session: "Sessão de caixa EUA",
    value: "Valor do livro",
    day: "P/L da sessão",
    nightPnl: "After-hours",
    multiplier: "Multiplicador UI",
    shares: "Ações",
    how: "Como funciona",
    pickWallet: "Escolha uma carteira",
    pickWalletBody: "O ShareExact lê Stock Tokens ativos na chain 4663. Não custodia chaves.",
    noWallet: "Sem carteira no browser. Instale MetaMask ou Rabby e volte.",
    scanning: "A ler Stock Tokens em 4663…",
    emptyBook: "Este endereço não tem Stock Tokens ativos na Robinhood Chain.",
    refreshBook: "Atualizar carteira",
    switchNetwork: "Mudar para Robinhood Chain",
    titleBrief: "Um brief antes de olhar.",
    titleHoldings: "O livro, em ações de corretora.",
    titleThesis: "Afirme uma crença. Obtenha um livro.",
    titleNight: "A sessão de caixa está escura.",
    titleTransfer: "Envie o número que a chain realmente vai mover.",
    help1: "Os Stock Tokens mostram ações de corretora. A carteira guarda um ERC-20 cru diferente. CRWD é 4×.",
    help2: "O brief diário e semanal leem este livro. Nada corre até carregar no botão.",
    help3: "A tese mapeia uma frase para tokens da 4663. A mesa noturna é a fita com a NYSE às escuras.",
    close: "Fechar",
    language: "Idioma",
    activity: "Atividade",
    replacements: "Substituições",
    calendar: "Calendário",
    risks: "Riscos",
    watchTonight: "Ver esta noite",
    weight: "Peso",
    nameCol: "Nome",
    tapeCol: "Fita",
    wrongChain: "A carteira está na rede errada.",
    onChain: "Livro on-chain",
    sampleHint: "Explore a mesa de exemplo, ou ligue uma carteira com Stock Tokens.",
    foundInWallet: "nomes nesta carteira",
    via: "via",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  ru: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "Точные акции. После закрытия. Бриф до взгляда.",
    navBrief: "Бриф",
    navHoldings: "Портфель",
    navThesis: "Тезис",
    navNight: "Ночной стол",
    navTransfer: "Точная отправка",
    navRisk: "Риск и кредит",
    loadDesk: "Загрузить демо-стол",
    resetDesk: "Сбросить демо",
    connect: "Подключить кошелёк",
    connected: "Подключено",
    disconnect: "Отключить",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "Демо-стол",
    runBrief: "Бриф сегодня",
    runWeekly: "Недельный обзор",
    running: "Читаем книгу…",
    briefEmpty: "Стол не гадает. Запустите бриф, чтобы прочитать книгу.",
    weeklyEmpty: "Недельный обзор проверяет концентрацию, after-hours и устаревший оракул.",
    thesisHint: "Сформулируйте убеждение. Стол перенесёт его на токены сети 4663.",
    thesisPlaceholder: "ИИ-инфраструктура ещё два года компаундится, но без ставки только на NVDA.",
    compose: "Собрать корзину",
    applyBasket: "Применить как бумажную книгу",
    nightIntro: "Уолл-стрит спит. Эти токены — нет. Ночной стол — лента after-hours.",
    transferIntro: "Число на экране брокера — не то, что отправляет кошелёк. ShareExact конвертирует до подписи.",
    amount: "Акций к отправке",
    recipient: "Получатель (пусто = вы)",
    preview: "Предпросмотр точной суммы",
    sendDemo: "Записать демо-отправку",
    max: "Макс",
    trapTitle: "Что отправит наивный кошелёк",
    exactTitle: "Что реально сдвинет сеть",
    holdingsIntro: "Количество акций использует живой UI-множитель, как на экране брокера.",
    clickHint: "Откройте имя, чтобы увидеть все углы.",
    legal: "Не является предложением ценных бумаг. Индикативные котировки. Не финсовет.",
    analyze: "Разобрать это имя",
    replace: "Замена",
    hold: "Держать",
    trim: "Сократить",
    add: "Добавить",
    stance: "Позиция",
    session: "Кэш-сессия США",
    value: "Стоимость книги",
    day: "P/L сессии",
    nightPnl: "After-hours",
    multiplier: "UI-множитель",
    shares: "Акции",
    how: "Как это работает",
    pickWallet: "Выберите кошелёк",
    pickWalletBody: "ShareExact читает активные Stock Tokens в сети 4663. Ключи не кастодиальные.",
    noWallet: "Кошелёк браузера не найден. Установите MetaMask или Rabby.",
    scanning: "Читаем Stock Tokens в 4663…",
    emptyBook: "На этом адресе нет активных Stock Tokens в Robinhood Chain.",
    refreshBook: "Обновить портфель",
    switchNetwork: "Переключить на Robinhood Chain",
    titleBrief: "Бриф до взгляда.",
    titleHoldings: "Книга в брокерских акциях.",
    titleThesis: "Сформулируйте веру. Получите книгу.",
    titleNight: "Кэш-сессия тёмная.",
    titleTransfer: "Отправьте число, которое сеть реально сдвинет.",
    help1: "Stock Tokens показывают брокерские акции. Кошелёк хранит другой сырой ERC-20. CRWD = 4×.",
    help2: "Дневной и недельный бриф читают эту книгу. Ничего не запускается, пока не нажмёте кнопку.",
    help3: "Тезис переносит фразу на токены 4663. Ночной стол — лента, пока NYSE тёмная.",
    close: "Закрыть",
    language: "Язык",
    activity: "Активность",
    replacements: "Замены",
    calendar: "Календарь",
    risks: "Риски",
    watchTonight: "Смотреть сегодня ночью",
    weight: "Вес",
    nameCol: "Имя",
    tapeCol: "Лента",
    wrongChain: "Кошелёк в неверной сети.",
    onChain: "Ончейн-книга",
    sampleHint: "Посмотрите демо-стол или подключите кошелёк со Stock Tokens.",
    foundInWallet: "имён в этом кошельке",
    via: "через",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  tr: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "Tam hisse. Seans dışı. Bakmadan önce brif.",
    navBrief: "Brif",
    navHoldings: "Portföy",
    navThesis: "Tez",
    navNight: "Gece masası",
    navTransfer: "Tam gönderim",
    navRisk: "Risk ve kredi",
    loadDesk: "Örnek masayı yükle",
    resetDesk: "Örneği sıfırla",
    connect: "Cüzdan bağla",
    connected: "Bağlı",
    disconnect: "Bağlantıyı kes",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "Örnek masa",
    runBrief: "Bugünün brifi",
    runWeekly: "Haftalık inceleme",
    running: "Defter okunuyor…",
    briefEmpty: "Masa tahmin etmez. Defteri okumak için brifi çalıştırın.",
    weeklyEmpty: "Haftalık inceleme yoğunlaşma, seans dışı ve bayat oracle riskini bakar.",
    thesisHint: "Bir inanç yazın. Masa bunu 4663 zincirindeki gerçek tokenlara oturtur.",
    thesisPlaceholder: "YZ altyapısı iki yıl daha bileşik büyür ama tek isimli NVDA bahsi istemem.",
    compose: "Sepet oluştur",
    applyBasket: "Kâğıt defter olarak uygula",
    nightIntro: "Wall Street uyur. Bu tokenlar uyumaz. Gece masası seans dışı şerittir.",
    transferIntro: "Aracı ekranındaki sayı cüzdanın gönderdiği sayı değildir. İmza öncesi dönüştürür.",
    amount: "Gönderilecek hisse",
    recipient: "Alıcı (boş = siz)",
    preview: "Tam tutarı önizle",
    sendDemo: "Demo gönderimi kaydet",
    max: "Maks",
    trapTitle: "Naif bir cüzdanın göndereceği",
    exactTitle: "Zincirin gerçekten taşıyacağı",
    holdingsIntro: "Hisse sayısı canlı UI çarpanını kullanır; aracı ekranıyla eşleşir.",
    clickHint: "Tüm açıları görmek için bir isim açın.",
    legal: "Menkul kıymet teklifi değildir. Gösterim fiyatları. Yatırım tavsiyesi değil.",
    analyze: "Bu ismi analiz et",
    replace: "Yedek",
    hold: "Tut",
    trim: "Azalt",
    add: "Ekle",
    stance: "Durum",
    session: "ABD nakit seansı",
    value: "Defter değeri",
    day: "Seans K/Z",
    nightPnl: "Seans dışı",
    multiplier: "UI çarpanı",
    shares: "Hisse",
    how: "Nasıl çalışır",
    pickWallet: "Cüzdan seçin",
    pickWalletBody: "ShareExact 4663’teki aktif hisse tokenlarını okur. Anahtar saklamaz.",
    noWallet: "Tarayıcı cüzdanı yok. MetaMask veya Rabby kurup dönün.",
    scanning: "4663’teki hisse tokenları okunuyor…",
    emptyBook: "Bu adreste Robinhood Chain’de aktif hisse tokenı yok.",
    refreshBook: "Portföyü yenile",
    switchNetwork: "Robinhood Chain’e geç",
    titleBrief: "Bakmadan önce bir brif.",
    titleHoldings: "Defter, aracı hissesi olarak.",
    titleThesis: "Bir inanç yazın. Bir defter alın.",
    titleNight: "Nakit seansı karanlık.",
    titleTransfer: "Zincirin gerçekten taşıyacağı sayıyı gönderin.",
    help1: "Robinhood hisse tokenları aracı hisse sayısını gösterir. Cüzdan farklı ham ERC-20 tutar. CRWD 4×.",
    help2: "Günlük ve haftalık brif bu defteri okur. Düğmeye basana kadar çalışmaz.",
    help3: "Tez bir cümleyi 4663 tokenlarına oturtur. Gece masası NYSE kapalıyken şerittir.",
    close: "Kapat",
    language: "Dil",
    activity: "Aktivite",
    replacements: "Değişimler",
    calendar: "Takvim",
    risks: "Riskler",
    watchTonight: "Bu gece izle",
    weight: "Ağırlık",
    nameCol: "Ad",
    tapeCol: "Şerit",
    wrongChain: "Cüzdan yanlış ağda.",
    onChain: "Zincir defteri",
    sampleHint: "Örnek masayla gezin veya hisse tokenı olan bir cüzdan bağlayın.",
    foundInWallet: "isim bu cüzdanda",
    via: "ile",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  de: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "Exakte Aktien. After hours. Ein Briefing, bevor Sie schauen.",
    navBrief: "Briefing",
    navHoldings: "Bestand",
    navThesis: "These",
    navNight: "Nachtschicht",
    navTransfer: "Exakter Versand",
    navRisk: "Risiko & Kredit",
    loadDesk: "Beispieldesk laden",
    resetDesk: "Beispiel zurücksetzen",
    connect: "Wallet verbinden",
    connected: "Verbunden",
    disconnect: "Trennen",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "Beispieldesk",
    runBrief: "Heutiges Briefing",
    runWeekly: "Wöchentliche Prüfung",
    running: "Buch wird gelesen…",
    briefEmpty: "Der Desk rät nicht. Starten Sie ein Briefing, um das Buch zu lesen.",
    weeklyEmpty: "Die Wochenprüfung prüft Konzentration, After-Hours und veraltete Orakel.",
    thesisHint: "Formulieren Sie eine Überzeugung. Der Desk mappt sie auf Token der Chain 4663.",
    thesisPlaceholder: "KI-Infrastruktur verzinst sich zwei Jahre weiter, aber kein Single-Name-NVDA.",
    compose: "Korb erstellen",
    applyBasket: "Als Papierbuch übernehmen",
    nightIntro: "Die Wall Street schläft. Diese Token nicht. Die Nachtschicht ist das After-Hours-Band.",
    transferIntro: "Die Zahl auf dem Broker-Screen ist nicht die, die das Wallet sendet. ShareExact rechnet vor der Signatur um.",
    amount: "Zu sendende Aktien",
    recipient: "Empfänger (leer = Sie)",
    preview: "Exakten Betrag anzeigen",
    sendDemo: "Demo-Versand protokollieren",
    max: "Max",
    trapTitle: "Was ein naives Wallet senden würde",
    exactTitle: "Was die Chain tatsächlich bewegt",
    holdingsIntro: "Die Stückzahl nutzt den Live-UI-Multiplikator, damit sie dem Broker-Screen entspricht.",
    clickHint: "Öffnen Sie einen Namen für alle Blickwinkel.",
    legal: "Kein Wertpapierangebot. Indikative Kurse. Keine Anlageberatung.",
    analyze: "Diesen Namen analysieren",
    replace: "Ersatz",
    hold: "Halten",
    trim: "Reduzieren",
    add: "Aufstocken",
    stance: "Haltung",
    session: "US-Cash-Session",
    value: "Buchwert",
    day: "Session-GuV",
    nightPnl: "After-hours",
    multiplier: "UI-Multiplikator",
    shares: "Aktien",
    how: "So funktioniert es",
    pickWallet: "Wallet wählen",
    pickWalletBody: "ShareExact liest aktive Stock Tokens auf Chain 4663. Keine Schlüsselverwahrung.",
    noWallet: "Kein Browser-Wallet. MetaMask oder Rabby installieren, dann zurück.",
    scanning: "Stock Tokens auf 4663 werden gelesen…",
    emptyBook: "Diese Adresse hält keine aktiven Stock Tokens auf Robinhood Chain.",
    refreshBook: "Bestand aktualisieren",
    switchNetwork: "Zu Robinhood Chain wechseln",
    titleBrief: "Ein Briefing, bevor Sie schauen.",
    titleHoldings: "Das Buch in Broker-Aktien.",
    titleThesis: "Eine Überzeugung. Ein Buch.",
    titleNight: "Die Cash-Session ist dunkel.",
    titleTransfer: "Senden Sie die Zahl, die die Chain wirklich bewegt.",
    help1: "Robinhood Stock Tokens zeigen Broker-Aktien. Das Wallet hält eine andere rohe ERC-20-Zahl. CRWD ist 4×.",
    help2: "Tages- und Wochenbriefing lesen dieses Buch. Nichts läuft, bis Sie drücken.",
    help3: "Die These mappt einen Satz auf Token der 4663. Die Nachtschicht ist das Band bei dunkler NYSE.",
    close: "Schließen",
    language: "Sprache",
    activity: "Aktivität",
    replacements: "Ersatz",
    calendar: "Kalender",
    risks: "Risiken",
    watchTonight: "Heute Nacht beobachten",
    weight: "Gewicht",
    nameCol: "Name",
    tapeCol: "Band",
    wrongChain: "Wallet ist im falschen Netz.",
    onChain: "On-Chain-Buch",
    sampleHint: "Mit dem Beispieldesk touren oder ein Wallet mit Stock Tokens verbinden.",
    foundInWallet: "Namen in diesem Wallet",
    via: "über",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
  fr: {
    app: "ShareExact",
    kicker: "Robinhood Chain · 4663",
    tagline: "Actions exactes. After hours. Un brief avant de regarder.",
    navBrief: "Brief",
    navHoldings: "Portefeuille",
    navThesis: "Thèse",
    navNight: "Bureau de nuit",
    navTransfer: "Envoi exact",
    navRisk: "Risque et crédit",
    loadDesk: "Charger le bureau d’exemple",
    resetDesk: "Réinitialiser l’exemple",
    connect: "Connecter le portefeuille",
    connected: "Connecté",
    disconnect: "Déconnecter",
    profile: "Profile",
    saveProfile: "Save profile",
    deskName: "Desk name",
    handle: "Handle",
    motto: "Motto",
    copyAddress: "Copy address",
    chain: "Robinhood Chain 4663",

    demoMode: "Bureau d’exemple",
    runBrief: "Brief du jour",
    runWeekly: "Revue hebdomadaire",
    running: "Lecture du livre…",
    briefEmpty: "Le bureau ne devine pas. Lancez un brief pour lire le livre.",
    weeklyEmpty: "La revue hebdo couvre concentration, after-hours et oracle périmé.",
    thesisHint: "Énoncez une conviction. Le bureau la projette sur les tokens réels de la chaîne 4663.",
    thesisPlaceholder: "L’infra IA se capitalise encore deux ans, sans pari unique sur NVDA.",
    compose: "Composer le panier",
    applyBasket: "Appliquer comme livre papier",
    nightIntro: "Wall Street dort. Ces tokens non. Le bureau de nuit est la bande after-hours.",
    transferIntro: "Le chiffre à l’écran du courtier n’est pas celui que le portefeuille envoie. ShareExact convertit avant la signature.",
    amount: "Actions à envoyer",
    recipient: "Destinataire (vide = vous)",
    preview: "Prévisualiser le montant exact",
    sendDemo: "Enregistrer un envoi démo",
    max: "Max",
    trapTitle: "Ce qu’enverrait un portefeuille naïf",
    exactTitle: "Ce que la chaîne va réellement déplacer",
    holdingsIntro: "Le nombre d’actions utilise le multiplicateur UI live pour coller à l’écran courtier.",
    clickHint: "Ouvrez un nom pour tous les angles.",
    legal: "Ceci n’est pas une offre de titres. Cours indicatifs. Pas un conseil financier.",
    analyze: "Analyser ce nom",
    replace: "Remplaçant",
    hold: "Conserver",
    trim: "Réduire",
    add: "Renforcer",
    stance: "Posture",
    session: "Séance cash US",
    value: "Valeur du livre",
    day: "P/L de séance",
    nightPnl: "After-hours",
    multiplier: "Multiplicateur UI",
    shares: "Actions",
    how: "Comment ça marche",
    pickWallet: "Choisir un portefeuille",
    pickWalletBody: "ShareExact lit les Stock Tokens actifs sur la chaîne 4663. Pas de garde des clés.",
    noWallet: "Aucun portefeuille navigateur. Installez MetaMask ou Rabby puis revenez.",
    scanning: "Lecture des Stock Tokens sur 4663…",
    emptyBook: "Cette adresse ne détient aucun Stock Token actif sur Robinhood Chain.",
    refreshBook: "Actualiser le portefeuille",
    switchNetwork: "Passer sur Robinhood Chain",
    titleBrief: "Un brief avant de regarder.",
    titleHoldings: "Le livre, en actions de courtier.",
    titleThesis: "Énoncez une croyance. Obtenez un livre.",
    titleNight: "La séance cash est sombre.",
    titleTransfer: "Envoyez le chiffre que la chaîne va vraiment déplacer.",
    help1: "Les Stock Tokens affichent des actions de courtier. Le portefeuille détient un ERC-20 brut différent. CRWD = 4×.",
    help2: "Les briefs quotidien et hebdo lisent ce livre. Rien ne tourne tant que vous n’appuyez pas.",
    help3: "La thèse projette une phrase sur les tokens 4663. Le bureau de nuit est la bande quand le NYSE est sombre.",
    close: "Fermer",
    language: "Langue",
    activity: "Activité",
    replacements: "Remplacements",
    calendar: "Calendrier",
    risks: "Risques",
    watchTonight: "À surveiller ce soir",
    weight: "Poids",
    nameCol: "Nom",
    tapeCol: "Bande",
    wrongChain: "Le portefeuille est sur le mauvais réseau.",
    onChain: "Livre on-chain",
    sampleHint: "Parcourez le bureau d’exemple, ou connectez un portefeuille qui détient des Stock Tokens.",
    foundInWallet: "noms dans ce portefeuille",
    via: "via",
    titleRisk: "Stocks as collateral. Exact units first.",
    riskIntro: "The Risk Engine is deterministic: multiplier, concentration, volatility, and leverage. AI may translate a goal into policy. It never moves funds.",
    health: "Health",
    collateral: "Collateral capacity",
    borrow: "Credit line",
    utilization: "Utilization",
    leverage: "Leverage",
    concentration: "Concentration",
    volatility: "Volatility",
    judgePath: "Judge path",
    unlockLiquidity: "Unlock liquidity",
    stressBook: "Stress the book",
    playJudge: "Play 60s path",
    protect: "PROTECT",
    reduce: "REDUCE",
    monitor: "MONITOR",
    noAction: "NO ACTION",
    repay: "Repay",
    addCollateral: "Add collateral",
    corpAction: "Corporate action",
    runSplit: "Simulate AAPL 4:1 split",
    undoSplit: "Undo split",
    splitIntro: "A 4:1 split multiplies UI shares and the ERC-8056 multiplier, cuts the cash mark, and leaves raw units, debt, value and health unchanged.",
    rawUnchanged: "Raw units unchanged",
    debtUnchanged: "Debt unchanged",
    exposureUnchanged: "Economic exposure unchanged",
    healthUnchanged: "Health unchanged — unlike a market shock",
    exactSendCta: "See the CRWD 4× trap",
    exactness: "Exactness",
    crwdTrap: "CRWD’s live UI multiplier is 4×. Sending the brokerage number as raw would move four times the economic units. Exact send refuses rather than rounding.",
    borrowHint: "Demo credit line — no live vault. Dragging this slider must change Health. That is the point.",
    safetyRule: "AI may translate intent. This engine owns the numbers. A contract would own the limits.",
    passport: "RWA risk passport",
    registryLive: "official assets on 4663",
    liq: "Liquidation LTV",
    drawdown: "Drawdown",
    healthDropNote: "The model reacts to this book, not a generic headline.",
    stressEmpty: "Run a scenario. Health should move. Then run the split — health should not.",
    dustBanner: "This wallet’s Stock Tokens are dust-sized. Risk & credit is built for a real book — load the sample desk for the judge path.",
    unpriced: "No mark",
    dustBadge: "Dust book",
    prices: "Prices",
    indicativeMarks: "indicative demo marks — no feed configured",
    chainlinkOn: "Chainlink · chain 4663",
    sequencer: "sequencer",
    sequencerUp: "up",
    sequencerDown: "down",
    oldestPrint: "oldest print",
    unitUnreadable: "unit unreadable",
    blankSelf: "Blank = yourself",
    defaultDesk: "Desk",
    sendExact: "Send exact shares",
    instruction: "Instruction",
    whatWillMove: "What will move",
    readingToken: "Reading the token on chain…",
    insufficientRaw: "Raw wallet balance cannot cover this amount.",
    badRecipient: "Recipient is not a valid address. Leave blank to send to yourself.",
    acceptLoss: "Accept the rounding shortfall to send.",
    acceptShortfall: "This amount is not exactly representable. Accept losing {n} wei of a share.",
    unitUnknownDetail:
      "Their uiMultiplier could not be read from the token. The registry value is shown for reference only and no share-denominated transfer will execute against them: an unknown ratio is not assumed to be 1:1.",
  },
};

export const WRITE_LANG: Record<Lang, string> = {
  en: "Write in concise English.",
  fa: "Write every string value in Persian (Farsi). Keep ticker symbols in Latin.",
  ar: "Write every string value in Arabic. Keep ticker symbols in Latin.",
  es: "Write every string value in Spanish. Keep ticker symbols in Latin.",
  zh: "Write every string value in Simplified Chinese. Keep ticker symbols in Latin.",
  ko: "Write every string value in Korean. Keep ticker symbols in Latin.",
  ja: "Write every string value in Japanese. Keep ticker symbols in Latin.",
  pt: "Write every string value in Portuguese. Keep ticker symbols in Latin.",
  ru: "Write every string value in Russian. Keep ticker symbols in Latin.",
  tr: "Write every string value in Turkish. Keep ticker symbols in Latin.",
  de: "Write every string value in German. Keep ticker symbols in Latin.",
  fr: "Write every string value in French. Keep ticker symbols in Latin.",
};
