#!/usr/bin/env node
/**
 * Sync Chainlink feed addresses for Robinhood Chain Stock Tokens.
 *
 * Why this is a script and not a constants file: Robinhood's documentation
 * points integrators at Chainlink's published feed list as the source of truth
 * for addresses, decimals and heartbeats. Pinning them in source means shipping
 * a stale address the first time a feed is migrated, and a stale feed address
 * is indistinguishable from a dead market.
 *
 * Usage:
 *   npm run feeds:sync                      # uses FEED_DIRECTORY_URL
 *   FEED_DIRECTORY_URL=https://... npm run feeds:sync
 *   npm run feeds:sync -- --from ./feeds.json
 *
 * Accepted input shapes:
 *   A) Chainlink reference-data-directory: an array of entries with
 *      { proxyAddress|contractAddress, pair|name, decimals, heartbeat }
 *   B) A flat object: { "NVDA": "0xfeed..." }
 *   C) A full object: { "NVDA": { feed, maxStaleness, decimals } }
 *
 * The output is written to src/lib/feeds.generated.json and is the only file
 * the app reads. Nothing here talks to the chain, so it is safe to run in CI.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";

const OUTPUT = resolve("src/lib/feeds.generated.json");
const DEFAULT_STALENESS = 26 * 60 * 60; // sized for a 24/5 equity feed
const DEFAULT_DECIMALS = 8;
const ADDRESS = /^0x[a-fA-F0-9]{40}$/;

function arg(flag) {
  const i = process.argv.indexOf(flag);
  return i > -1 ? process.argv[i + 1] : undefined;
}

function symbolFromPair(entry) {
  const raw =
    entry.pair?.[0] ??
    entry.name ??
    entry.assetName ??
    entry.docs?.baseAsset ??
    entry.path ??
    "";
  const text = Array.isArray(raw) ? raw[0] : String(raw);
  const base = text.split("/")[0].trim().toUpperCase();
  // "NVDA", "NVDA STOCK TOKEN", "TOKENIZED NVDA" all collapse to a ticker.
  const match = base.match(/[A-Z]{1,6}/g);
  return match ? match[match.length === 1 ? 0 : 0] : "";
}

function fromDirectory(list) {
  const feeds = {};
  for (const entry of list) {
    const address = entry.proxyAddress ?? entry.contractAddress ?? entry.address;
    if (!address || !ADDRESS.test(address)) continue;
    const symbol = symbolFromPair(entry);
    if (!symbol) continue;
    const heartbeat = Number(entry.heartbeat ?? entry.threshold ?? 0);
    feeds[symbol] = {
      feed: address,
      // Give the published heartbeat real headroom: a feed that is a few
      // minutes late is not a dead feed, and flapping into STALE every evening
      // would train users to ignore the warning that matters.
      maxStaleness: heartbeat > 0 ? Math.max(heartbeat * 2, 3600) : DEFAULT_STALENESS,
      decimals: Number.isInteger(entry.decimals) ? entry.decimals : DEFAULT_DECIMALS,
    };
  }
  return feeds;
}

function fromObject(object) {
  const feeds = {};
  for (const [symbol, value] of Object.entries(object)) {
    const entry = typeof value === "string" ? { feed: value } : value ?? {};
    if (!entry.feed || !ADDRESS.test(entry.feed)) continue;
    feeds[symbol.toUpperCase()] = {
      feed: entry.feed,
      maxStaleness: Number(entry.maxStaleness) > 0 ? Number(entry.maxStaleness) : DEFAULT_STALENESS,
      decimals: Number.isInteger(entry.decimals) ? entry.decimals : DEFAULT_DECIMALS,
    };
  }
  return feeds;
}

async function load() {
  const file = arg("--from");
  if (file) {
    const text = await readFile(resolve(file), "utf8");
    return { source: `file:${file}`, payload: JSON.parse(text) };
  }
  const url = arg("--url") ?? process.env.FEED_DIRECTORY_URL;
  if (!url) {
    throw new Error(
      "No source. Pass --from <file>, --url <url>, or set FEED_DIRECTORY_URL to the Chainlink feed directory for chain 4663.",
    );
  }
  const res = await fetch(url, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`${url} returned HTTP ${res.status}`);
  return { source: url, payload: await res.json() };
}

async function main() {
  const { source, payload } = await load();
  const feeds = Array.isArray(payload)
    ? fromDirectory(payload)
    : Array.isArray(payload?.feeds)
      ? fromDirectory(payload.feeds)
      : fromObject(payload?.feeds ?? payload);

  const count = Object.keys(feeds).length;
  if (count === 0) {
    throw new Error(
      "Parsed zero usable feeds. Check the source shape — expected an array of directory entries or a { SYMBOL: address } object.",
    );
  }

  const output = {
    source,
    generatedAt: new Date().toISOString(),
    note: "Generated by scripts/fetch-feeds.mjs. Do not edit by hand; re-run npm run feeds:sync.",
    feeds,
  };

  await writeFile(OUTPUT, `${JSON.stringify(output, null, 2)}\n`, "utf8");
  console.log(`wrote ${count} feeds to ${OUTPUT}`);
  for (const [symbol, cfg] of Object.entries(feeds).slice(0, 10)) {
    console.log(`  ${symbol.padEnd(6)} ${cfg.feed}  staleness ${cfg.maxStaleness}s`);
  }
  if (count > 10) console.log(`  … and ${count - 10} more`);
}

main().catch((err) => {
  console.error(`feeds:sync failed — ${err.message}`);
  process.exitCode = 1;
});
